/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lanchat2;

import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;



/**
 *
 * @author sooryagangarajk
 */
public class LanChatFrame extends javax.swing.JFrame {
   
    /**
     * Creates new form LanChatFrame
     */
    public LanChatFrame() {
        initComponents();
    }
    
   // This method will print the string in the text box 
   public void msgOut(String str){
       String temp=outputbox.getText()+"\n";
       outputbox.setText(temp+str);
   }
   public void setMyIpAddress(String str){
       myIp.setText(str);
   }
   
   public static boolean ip(String text) {// this method will check wether the given string is ip address or not
    Pattern p = Pattern.compile("^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$");
    Matcher m = p.matcher(text);//// S G K ////0xpulsar////
    return m.find();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        myIp = new javax.swing.JLabel();
        ipbox = new javax.swing.JTextField();
        msgBox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputbox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAN CHAT");

        myIp.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        myIp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myIp.setText(" ");

        ipbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ipbox.setText("Enter the ip address");
        ipbox.setToolTipText("");
        ipbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ipboxMouseClicked(evt);
            }
        });
        ipbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipboxActionPerformed(evt);
            }
        });

        msgBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        msgBox.setText("Message");
        msgBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msgBoxMouseClicked(evt);
            }
        });
        msgBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgBoxActionPerformed(evt);
            }
        });

        outputbox.setColumns(20);
        outputbox.setRows(5);
        jScrollPane1.setViewportView(outputbox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msgBox)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(myIp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ipbox, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myIp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ipboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipboxActionPerformed
        // This will check for:
        //* The String contains ip address or not
        if(ip(ipbox.getText())){
          
            try {
                LanChat2.setClientIP(ipbox.getText());
            } catch (UnknownHostException ex) {//// S G K //// 0xpulsar ////
                Logger.getLogger(LanChatFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        ipbox.setText("Chatting with "+ipbox.getText());
        }else
        {
            //invalid Ip Address shows
            ipbox.setText("Invalid ip address");
        }
    }//GEN-LAST:event_ipboxActionPerformed

    private void ipboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipboxMouseClicked
        
        //clears the text on the box when mouse clicked on it
        ipbox.setText("");
    }//GEN-LAST:event_ipboxMouseClicked

    private void msgBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msgBoxMouseClicked
        
        //clears the text on the box when mouse clicked on it
        msgBox.setText("");
    }//GEN-LAST:event_msgBoxMouseClicked

    private void msgBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgBoxActionPerformed
        //when the user press enter this method is called
        try {
            
            //Sends the text in the field to msgSend method in the main class
            LanChat2.msgSend(msgBox.getText());
        } catch (IOException ex) {//// S G K //// 0xpulsar ////
            Logger.getLogger(LanChatFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //After that it will clear the text on the field
        msgBox.setText("");
    }//GEN-LAST:event_msgBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LanChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LanChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LanChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LanChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LanChatFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ipbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField msgBox;
    private javax.swing.JLabel myIp;
    private javax.swing.JTextArea outputbox;
    // End of variables declaration//GEN-END:variables
}
